### ISSUE TITLE
Invalid Pin Issue

### ISSUE THREAD

**Issue by d4n1l3dm4tr1x** [BenjaminFaal/ps4-remote-pkg-installer#1]
Hi! So I dont know if this is because my ps4 is on 7.02 but everytime I try to connect the app to the ps4 via manual login PSN it says "Invalid Pin, please enter a valid pin from the PS4 Mobile app connection settings." and I could not figure out what that meant because Id insert the pin from the PS4 remote play settings (from the ps4) and it wouldnt work. Thanks for the app tho!

**Comment by BenjaminFaal** [comment]
Mine is on 7.02 too, you need to enter a pin not from remote play but from mobile app connection settings: https://manuals.playstation.net/document/gb/ps4/settings/app.html
