### ISSUE TITLE
"URI is not absolute" when selecting file

### ISSUE THREAD

**Issue by unresolvedsymbol** [BenjaminFaal/ps4-remote-pkg-installer#3]
Version 0.0.4 on Linux with OpenJDK/JRE "1.8.0_251". Not using the remote control feature.
Might file separators be the culprit? There's a keyword `File.separator` afaik
Backtrace: https://asciinema.org/a/L8KnaT3rwogw2v6ZBR7Jd2RPk
![popup](https://user-images.githubusercontent.com/48220091/105615211-b9614700-5dc6-11eb-8f48-77ad7c30d919.png)

**Comment by BenjaminFaal** [comment]
What is the filename and path?

**Comment by unresolvedsymbol** [comment]
It doesn't seem to matter. I tried moving the package to a simpler name and still no dice. `/home/void/nfs.pkg`

**Comment by BenjaminFaal** [comment]
I dont think it has to do with the filename/path but with the URL it uses to connect to the REST API of the Remote PKG Installer.
