### ISSUE TITLE
Installer not recognised on PS4

### ISSUE THREAD

**Issue by emmanuelddr** [BenjaminFaal/ps4-remote-pkg-installer#4]
Hi,

I use the other remote PKG senders very well but would love to try yours, but it fails to show listed as an app in the second-screen section of the PS4 - my mobile does appear OK - any idea ?

Thanks,

Emmanuel

**Comment by emmanuelddr** [comment]
Used login authentification instead, thanks.

**Comment by BenjaminFaal** [comment]
Everything needs to be on the same network (computer, PS4 Mobile App and PS4) maybe firewall is blocking port 987. Also most operating systems you need admin/root access to use port 987.
