### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by herojihn** [BenjaminFaal/ps4-remote-pkg-installer#5]
I'm sorry that I'm having issue with 0.0.7 version. It says as below. Could you please kindly help? Thank you so much!
org.springframework.web.client.ResourceAccessException:I/O error on POST request for "http://192.168.1.218:12800/api/install": Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out

**Comment by BenjaminFaal** [comment]
That means that either Remote PKG Installer is not running or the API is corrupted, see https://github.com/flatz/ps4_remote_pkg_installer/issues/3

**Comment by herojihn** [comment]
Thank you so much!!!
