### ISSUE TITLE
PS4 without PSN account

### ISSUE THREAD

**Issue by piterq** [BenjaminFaal/ps4-remote-pkg-installer#8]
I've got "Invalid PIN" error when trying to authenticate. Does this app work if PS4 was never connected to PSN (there is no PSN account on PS4)?

**Comment by al10capote** [comment]
I wish this app work without internet,please

**Comment by BenjaminFaal** [comment]
You can work around this by disabling the Remote control option. However you have to manually start Remote PKG Installer on the PS4.
