### ISSUE TITLE
Error with Install PKG from URL option

### ISSUE THREAD

**Issue by Alterr87** [BenjaminFaal/ps4-remote-pkg-installer#9]
When installing pkg via URL, an error occurs, but the installation is successful.
![ice_video_20210127-215941 mp4_20210127_220844 071](https://user-images.githubusercontent.com/54379058/106041527-f55d1a80-60ec-11eb-8171-820eea0e36bc.png)
https://user-images.githubusercontent.com/54379058/106041998-9055f480-60ed-11eb-87ec-328eafb06633.mp4

**Comment by BenjaminFaal** [comment]
Its a known issue unfortunately: https://github.com/flatz/ps4_remote_pkg_installer/issues/3 you have to restart the Remote PKG Installer on the PS4.
